[program:school-push-worker]
process_name=%(program_name)s_%(process_num)02d
# I added your path below:
command=php /var/www/toyar/school-app.toyar.lk/public/artisan queue:work --queue=push-urgent,push-high,push-normal --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
# I added your path below:
stdout_logfile=/var/www/toyar/school-app.toyar.lk/public/storage/logs/push-worker.log
stopwaitsecs=3600